version: "3.9"
services:
sensor-noise:
build: .
image: sensor-noise-service:latest
container_name: sensor-noise
ports:
- "8080:8000" # expõe http://IP:8080
environment:
- UVICORN_HOST=0.0.0.0
- UVICORN_PORT=8000
healthcheck:
test: ["CMD-SHELL", "wget -qO- http://localhost:8000/docs || exit 1"]
interval: 10s
timeout: 3s
retries: 10
restart: unless-stopped
