version: "3.9"
services:
sensor-noise:
build: .
image: sensor-noise-service:latest
container_name: sensor-noise
# === VARIANTE 1 — expor por IP:porta ===
ports:
- "8091:8000" # acessa via http://SEU_IP:8091
# === VARIANTE 2 — comunicação container↔container (n8n na mesma rede) ===
# Se quiser, remova as ports acima e mantenha apenas a rede 'shared' para chamar
# http://sensor-noise:8000/process a partir do n8n
restart: unless-stopped
environment:
- UVICORN_HOST=0.0.0.0
- UVICORN_PORT=8000
healthcheck:
test: ["CMD-SHELL", "curl -sf http://localhost:8000/docs > /dev/null || exit 1"]
interval: 10s
timeout: 3s
retries: 10
start_period: 10s
networks:
- shared
